talent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('talentsystem.urls')),
    # path('api/', include('authy.api_urls')),

]

talentsystem/urls.py
from django.urls import path ,include
from . import views


urlpatterns = [
	path('', views.home, name='home'),
	# path('login/', views.login_user, name='login'),
	path('upload/', views.upload, name='upload'),
	path('logout/', views.logout_user, name='logout'),
	path('register/', views.register_user, name='register'),
	path('record/<int:pk>', views.company_record, name='record'),
	path('delete_company/<int:pk>', views.delete_company, name='delete_company'),
	path('add_record/', views.add_record, name='add_record'),
	path('update_company/<int:pk>', views.update_company, name='update_company'),



	path('employee_record/<int:pk>', views.employee_record, name='employee_record'),
	path('delete_employee/<int:pk>', views.delete_employee, name='delete_employee'),
	path('add_employee/', views.add_employee, name='add_employee'),
	path('update_employee/<int:pk>', views.update_employee, name='update_employee'),



	path('department_record/<int:pk>', views.department_record, name='department_record'),
	path('delete_department/<int:pk>', views.delete_department, name='delete_department'),
	path('add_department/', views.add_department, name='add_department'),
	path('update_department/<int:pk>', views.update_department, name='update_department'),


	path('company_details/', views.company_details, name='company_details'),
	path('search/', views.search_results, name='search_results'),


]

talentsystem/models.py
from django.db import models


# Company datails
class CompanyRecord(models.Model):
    company_name = models.CharField(max_length=100)
    company_reg_number = models.CharField(max_length=50)
    company_address = models.CharField(max_length=150)
    company_email = models.EmailField(max_length=100)
    contact_person = models.CharField(max_length=50)
    departments = models.CharField(max_length=300)
    contact_phone = models.CharField(max_length=50)
    number_of_employees = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    bulk = models.FileField(null=True, blank=True)

    def __str__(self):
        return f"{self.company_name}{self.company_reg_number}"


# Department Details table
class DepartmentRecord(models.Model):
    department_name = models.CharField(max_length=100)
    company = models.ForeignKey(CompanyRecord, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.id }{self.department_name}"


# Employee Details
class EmployeeRecord(models.Model):
    employee_name = models.CharField(max_length=100)
    employee_id = models.CharField(max_length=50)
    department = models.ForeignKey(
        DepartmentRecord, on_delete=models.SET_NULL, null=True
    )
    role = models.CharField(max_length=150)
    date_started = models.CharField(max_length=50)
    date_left = models.CharField(max_length=50)
    dutie = models.CharField(max_length=300)

    def __str__(self):
        return f"{self.employee_name}{self.employee_id}"

talentsystem/forms.py
import os
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import CompanyRecord, EmployeeRecord, DepartmentRecord
from django.core.exceptions import ValidationError
import csv

class SignUpForm(UserCreationForm):
	email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
	first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
	last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))


	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


	def __init__(self, *args, **kwargs):
		super(SignUpForm, self).__init__(*args, **kwargs)

		self.fields['username'].widget.attrs['class'] = 'form-control'
		self.fields['username'].widget.attrs['placeholder'] = 'User Name'
		self.fields['username'].label = ''
		self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

		self.fields['password1'].widget.attrs['class'] = 'form-control'
		self.fields['password1'].widget.attrs['placeholder'] = 'Password'
		self.fields['password1'].label = ''
		self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

		self.fields['password2'].widget.attrs['class'] = 'form-control'
		self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
		self.fields['password2'].label = ''
		self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'	




class AddCompanyRecord(forms.ModelForm):

	company_name = forms.CharField(required=True, widget =forms.widgets.TextInput(attrs={"placeholder":"Company Name", "class":"form-control"}),label="")
	company_reg_number = forms.CharField(required=True, widget =forms.widgets.TextInput(attrs={"placeholder":"Company Registration Number", "class":"form-control"}),label="")
	company_address = forms.CharField(required=True, widget =forms.widgets.TextInput(attrs={"placeholder":"Company Address", "class":"form-control"}),label="")
	contact_person = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Company Contact Person ", "class":"form-control"}),label="")
	departments = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Company Departments", "class":"form-control"}),label="")
	contact_phone = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Company ContactPhone", "class":"form-control"}),label="")
	number_of_employees = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Number of Employees", "class":"form-control"}),label="")
	company_email = forms.EmailField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"Company Email Address", "class":"form-control"}),label="")
	class Meta:
		model = CompanyRecord
		exclude = ("User",)


class AddEmployeeRecord(forms.ModelForm):

	employee_name = forms.CharField(required=True, widget =forms.widgets.TextInput(attrs={"placeholder":"| EMployee Name", "class":"form-control"}),label="")
	employee_id = forms.CharField(required=True, widget =forms.widgets.TextInput(attrs={"placeholder":"| Employee ID Number", "class":"form-control"}),label="")
	role = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"| Employee Role ", "class":"form-control"}),label="")
	date_started = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"| Date Started In Role(dd-mm-yyy)", "class":"form-control"}),label="")
	date_left = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"| Date Left Role (dd-mm-yyy)", "class":"form-control"}),label="")
	dutie = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder":"| Duty Served (Serving)", "class":"form-control"}),label="")
	class Meta:
		model = EmployeeRecord
		exclude = ("User",)

class AddDepartment(forms.ModelForm):
	department_name = forms.CharField(required=True, widget =forms.widgets.TextInput(attrs={"placeholder":"| Department Name", "class":"form-control"}),label="")
	
	class Meta:
		model = DepartmentRecord
		exclude = ("User",)



class UploadFileForm(forms.Form):
    file = forms.FileField(label='Select a file')

    def clean_file(self):
        uploaded_file = self.cleaned_data['file']
        if not uploaded_file.name.endswith('.csv'):
            raise forms.ValidationError("Only CSV files are allowed.")
        try:
            csv.reader(uploaded_file)
        except csv.Error:
            raise forms.ValidationError("Invalid CSV file.")
        return uploaded_file

talentsystem/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import (
    SignUpForm,
    AddCompanyRecord,
    AddEmployeeRecord,
    AddDepartment,
    UploadFileForm,
)
from .models import CompanyRecord, DepartmentRecord, EmployeeRecord
from cryptography.fernet import Fernet


# Create your views here.
def home(request):
    company_Records = CompanyRecord.objects.all()
    department_Records = DepartmentRecord.objects.all()
    employee_Records = EmployeeRecord.objects.all()

    # checking and logging in usrr
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "You Have Been Logged In!")
            return redirect("home")
        else:
            messages.success(
                request, "There Was An Error Logging In, Please Try Again..."
            )
            return redirect("home")
    else:
        context = {
            "company_Records": company_Records,
            "department_Records": department_Records,
            "employee_Records": employee_Records,
        }
        return render(request, "home.html", context)


def logout_user(request):
    logout(request)
    messages.success(request, "You Have Been Logged Out...")
    return redirect("home")


def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()

            # Authenticate and login

            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "You Have Successfully Registered! Welcome!")
            return redirect("home")
        else:
            form = SignUpForm()
            return render(request, "register.html", {"form": form})

    return render(request, "register.html", {})


# viewign individualcompany record
def company_record(request, pk):
    if request.user.is_authenticated:
        company_record = CompanyRecord.objects.get(id=pk)
        return render(request, "record.html", {"company_record": company_record})

    else:
        messages.success(request, "Login to View the record!.")
        return redirect("home")


def delete_company(request, pk):
    if request.user.is_authenticated:
        delete_company = CompanyRecord.objects.get(id=pk)
        delete_company.delete()
        messages.success(request, "Company deleted.")
        return redirect("home")
    else:
        messages.success(request, "You don't have the right to delete this record.")
        return redirect("home")


def add_record(request):
    form = AddCompanyRecord(request.POST or None)
    if request.user.is_authenticated:
        if request.method == "POST":
            if form.is_valid():
                add_record = form.save()
                messages.success(request, "Company Record Added!")
                return redirect("home")

        return render(request, "add_record.html", {"form": form})
    else:
        messages.success(request, "Log In To Add Record.")
        return redirect("home")


def update_company(request, pk):
    if request.user.is_authenticated:
        current_company = CompanyRecord.objects.get(id=pk)
        form = AddCompanyRecord(request.POST or None, instance=current_company)
        if form.is_valid():
            form.save()
            messages.success(request, "Company Updated.")
            return redirect("home")
        return render(request, "update_company.html", {"form": form})
    else:
        messages.success(request, "You must be looged in.")
        return redirect("home")


# Employee Records >>>>


def employee_record(request, pk):
    if request.user.is_authenticated:
        employee_record = EmployeeRecord.objects.get(id=pk)
        return render(
            request, "employee_record.html", {"employee_record": employee_record}
        )

    else:
        messages.success(request, "Login to View the record!.")
        return redirect("home")


# adding a new employee


def add_employee(request):
    form = AddEmployeeRecord(request.POST or None)
    if request.user.is_authenticated:
        if request.method == "POST":
            if form.is_valid():
                add_record = form.save()
                messages.success(request, "Employee  Added!")
                return redirect("home")

        return render(request, "add_employee.html", {"form": form})
    else:
        messages.success(request, "Log In To Add Record.")
        return redirect("home")


def update_employee(request, pk):
    if request.user.is_authenticated:
        current_employee = EmployeeRecord.objects.get(id=pk)
        form = AddEmployeeRecord(request.POST or None, instance=current_employee)
        if form.is_valid():
            form.save()
            messages.success(request, "Employee Updated.")
            return redirect("home")
        return render(request, "update_employee.html", {"form": form})
    else:
        messages.success(request, "looged in to modify.")
        return redirect("home")


def delete_employee(request, pk):
    if request.user.is_authenticated:
        delete_it = EmployeeRecord.objects.get(id=pk)
        delete_it.delete()
        messages.success(request, "Employee deleted.")
        return redirect("home")
    else:
        messages.success(request, "You don't have the right to delete this record.")
        return redirect("home")


# <<<<<End-Of-Employees-Records>>>>>>


# Start-of-Department-Records>>>


def department_record(request, pk):
    if request.user.is_authenticated:
        department_record = DepartmentRecord.objects.get(id=pk)
        return render(
            request, "department_record.html", {"department_record": department_record}
        )

    else:
        messages.success(request, "Login to View the record!.")
        return redirect("home")


# Adding a department


def add_department(request):
    form = AddDepartment(request.POST or None)
    if request.user.is_authenticated:
        if request.method == "POST":
            if form.is_valid():
                add_record = form.save()
                messages.success(request, "New Department Added.")
                return redirect("home")

        return render(request, "add_department.html", {"form": form})
    else:
        messages.success(request, "Log In To Add Record.")
        return redirect("home")


# Editing and updating the Departments Records>>>


def update_department(request, pk):
    if request.user.is_authenticated:
        current_department = DepartmentRecord.objects.get(id=pk)
        form = AddDepartment(request.POST or None, instance=current_department)
        if form.is_valid():
            form.save()
            messages.success(request, "Department Updated.")
            return redirect("home")
        return render(request, "update_department.html", {"form": form})
    else:
        messages.success(request, "looged in to modify.")
        return redirect("home")


# Deleting Department record>>>>
def delete_department(request, pk):
    if request.user.is_authenticated:
        delete_it = DepartmentRecord.objects.get(id=pk)
        delete_it.delete()
        messages.success(request, "Department deleted.")
        return redirect("home")
    else:
        messages.success(request, "You don't have the right to delete this record.")
        return redirect("home")


# Bulk Uploading Records


from django.shortcuts import render, redirect


def upload(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form = UploadFileForm(request.POST, request.FILES)
            if form.is_valid():
                file = form.cleaned_data["file"]
                record = CompanyRecord.objects.create(bulk=file)
                record.save()
                return HttpResponse(
                    "Company record uploaded via bulk upload with id "
                    + str(record.pk)
                    + " file: "
                    + str(record.bulk)
                )
        else:
            form = UploadFileForm()
            return render(request, "upload.html", {"form": form})
    else:
        return redirect(
            "home"
        )  # Redirect to the home page if the user is not authenticated


# All the Necessary Company Details
def company_details(request):
    companies = CompanyRecord.objects.all()
    return render(request, "company_details.html", {"companies": companies})


def search_results(request):
    search_query = request.GET.get("search_query")
    results = EmployeeRecord.objects.filter(employee_name__icontains=search_query)
    context = {
        "results": results,
        "search_query": search_query,
    }
    return render(request, "search_results.html", context)

talentsystem/templates/add_department.html
{%extends 'base.html'%}

{%block content%}

<div class="col-md-6 offset-md-3">
<h1>Add A New Department</h1>
<br/>

<form method="POST" action="{% url 'add_department' %}">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
  <button type="submit" class="btn btn-secondary">Add</button>

</form>
<br/>


<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>

</div>

{% endblock %}

talentsystem/templates/add_employee.html
{%extends 'base.html'%}

{%block content%}

<div class="col-md-6 offset-md-3">
<h1>Add Employee Record</h1>
<br/>

<form method="POST" action="{% url 'add_employee' %}">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
  <button type="submit" class="btn btn-secondary">Add</button>

</form>
<br/>


<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>

</div>

{% endblock %}

talentsystem/templates/add_record.html
{%extends 'base.html'%}

{%block content%}

<div class="col-md-6 offset-md-3">
<h1>Add Company Record</h1>
<br/>

<form method="POST" action="{% url 'add_record' %}">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
  <button type="submit" class="btn btn-secondary">Add Record</button>

</form>
<br/>


<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
</div>

{% endblock %}

talentsystem/templates/company_details.html
{% extends 'base.html' %}
{% load encryption_tags %}

{% block content %}
{% if user.is_authenticated%}
    <!-- Search Form -->
    <form method="GET" action="{% url 'search_results' %}">
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="search_query" placeholder="Search...">
            <button class="btn btn-primary" type="submit">Search</button>
        </div>
    </form>

    <table class="table table-striped table-hover table-bordered">
        <!-- Table Header -->
        <thead class="table-dark">
            <tr>
                <th scope="col">CompanyName</th>
                <th scope="col">Comp_Reg_Num</th>
                <th scope="col">comp_address</th>
                <th scope="col">comp_email</th>
                <th scope="col">contact_person</th>
                <th scope="col">contact_phone</th>
                <th scope="col">employees_No</th>
                <th scope="col">Employee</th>
                <th scope="col">department</th>
            </tr>
        </thead>
        <tbody>
            {% for company in companies %}
            <tr>
                <td>{{ company.company_name }}</td>
                <td>{{ company.company_reg_number }}</td>
                <td>{{ company.company_address }}</td>
                <td>{{ company.company_email }}</td>
                <td>{{ company.contact_person }}</td>
                <td>{{ company.contact_phone }}</td>
                <td>{{ company.number_of_employees }}</td>
                <td>
                    {% for department in company.departmentrecord_set.all %}
                    {% for employee in department.employeerecord_set.all %}
                    {{ employee.employee_name }} - {{ employee.role}}<br>  <!-- Encrypting employee role -->
                    {% endfor %}
                    {% endfor %}
                </td>
                <td>
                    {% for department in company.departmentrecord_set.all %}
                    {{ department.department_name }}<br>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br/>
    {% else %}


<div class="col-md-6 offset-md-3">

<h1>login</h1>

<form method="POST" action="{%url 'home' %}">
  {% csrf_token %}

  <div class="mb-3">
    <input type="text" class="form-control" name="username", placeholder="Username" required>
    
  </div><br/>
  <div class="mb-3">
    <input type="password" class="form-control" name="password", placeholder="Password" required>
  </div>
  <br/>
  <button type="submit" class="btn btn-secondary">Login</button>
  
</form>
</div>

{% endif %}
<br/><br/>
{% endblock %}

talentsystem/templates/department_record.html
{% extends 'base.html' %}
{% block content %}



<div class="card">
  <div class="card-header"><strong>
    	{{department_record.department_name}}
      {{department_record.department_name.id}}</strong>
  </div>
  <div class="card-body">




<p class="card-text">
<strong>Employee ID </strong>{{department_record.department_name}}
</p>

<p class="card-text">
<strong>ID: </strong>{{ department_record.id }}</p> 
  </div>
</div>

<br/><br/>
    
<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
{% if user.username == "admin" %}

<a href="{% url 'delete_department' department_record.id %}" class="btn btn-danger">Delete</a>

<a href="{% url 'update_department' department_record.id %}" class="btn btn-secondary">Update Record</a>
{% endif %}
{% endblock %}

talentsystem/templates/employee_record.html
{% extends 'base.html' %}
{% block content %}



<div class="card">
  <div class="card-header"><strong>
    	{{employee_record.employee_name}}
      {{employee_record.employee.id}}</strong>
  </div>
  <div class="card-body">




<p class="card-text">
<strong>Employee ID </strong>{{employee_record.employee_id}}
</p>

<p class="card-text">
<strong>Department: </strong>{{employee_record.department}}</p>

<p class="card-text">
<strong>Role: </strong>{{employee_record.role}}</p>

<p class="card-text">
<strong>Date Started </strong>{{employee_record.date_started}}</p>

<p class="card-text">
<strong>Date Left: </strong>{{employee_record.date_left}}</p>

<p class="card-text">
<strong>Duty: </strong>{{employee_record.dutie}}</p>

<p class="card-text">
<strong>ID: </strong>{{ employee_record.id }}</p> 
  </div>
</div>

<br/><br/>
    
<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
{% if user.username == "admin" %}

<a href="{% url 'delete_employee' employee_record.id %}" class="btn btn-danger">Delete</a>

<a href="{% url 'update_employee' employee_record.id %}" class="btn btn-secondary">Update Record</a>
{% endif %}
{% endblock %}

talentsystem/templates/home.html
{%extends 'base.html'%}

{% block content %}



{% if user.is_authenticated%}
<h1>Company Records</h1>

<!-- Displaying Company records  -->
<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">comp_name</th>
      <th scope="col">comp_reg</th>
      <th scope="col">comp_address</th>
      <th scope="col">comp_email</th>
      <th scope="col">contact_person</th>
      <th scope="col">departments</th>
      <th scope="col">contact_phone</th>
      <th scope="col">employees_No</th>
      <th scope="col">Date</th>
      <th scope="col">file</th>
    </tr>
  </thead>
  <tbody>

    
{% if company_Records %}
  {% for company_Record in company_Records %}
  <!-- iterating through company records to return each individual field -->
    <tr>
      <td><a href="{% url 'record' company_Record.id %}"> {{ company_Record.id }}</a></td>
      <td>{{ company_Record.company_name }} </td>
      <td>{{ company_Record.company_reg_number }}</td>
      <td>{{ company_Record.company_address }}</td>
      <td>{{ company_Record.company_email }}</td>
      <td>{{ company_Record.contact_person }}</td>
      <td>{{ company_Record.departments }}</td>
      <td>{{ company_Record.contact_phone }}</td>
      <td>{{ company_Record.number_of_employees }}</td>
      <td>{{ company_Record.created_at }}</td>
      <td>{{ company_Record.bulk }}</td>
     
    </tr>

      <br/>

  {% endfor %}
{% endif %}


    </tbody>
  </table>
  <br/><br/><br/>
  <!-- Showing Company Departments -->


<h1>Company Departments</h1>
<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">Department_ID</th>
      <th scope="col">Department_Name</th>
    </tr>
  </thead>
  <tbody>


{% if department_Records %}

<!-- iterating through records of the department -->

  {% for department_Record in department_Records %}
    <tr>
    
      <td><a href="{% url 'department_record' department_Record.id %}"> {{ department_Record.id }}</a></td>
      <td>{{department_Record.department_name}}</td>
     
    </tr>

      <br/>

  {% endfor %}
{% endif %}


 </tbody>
  </table>
  <br/><br/><br/>



<h1>Employee Records</h1>

<!-- Displaying Employee records   -->
<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">employee_id</th>
      <th scope="col">employee_name</th>
      <th scope="col">department</th>
      <th scope="col">role</th>
      <th scope="col">date_started</th>
      <th scope="col">date_left</th>
      <th scope="col">dutie</th>
      
    </tr>
  </thead>
  <tbody>

{% if employee_Records %}

<!-- Looping through all records in Employee-record model -->

  {% for employee_Record in employee_Records %}
    <tr>

      <td><a href="{% url 'employee_record' employee_Record.id %}"> {{ employee_Record.id }}</a></td>

      <td> {{employee_Record.employee_name}}</td>
      <td> {{employee_Record.department}}</td>
      <td> {{employee_Record.role}}</td>
      <td>{{employee_Record.date_started}}</td>
      <td>{{employee_Record.date_left}}</td>
      <td> {{employee_Record.dutie}}</td>
     
    </tr>

      <br/>

  {% endfor %}

{% endif %}

    </tbody>
  </table>
  <br/><br/><br/>
  <br/><br/><br/>




{% else %}
<div class="col-md-6 offset-md-3">

<h1>login</h1>

<form method="POST" action="{%url 'home' %}">
	{% csrf_token %}

	<div class="mb-3">
    <input type="text" class="form-control" name="username", placeholder="Username" required>
    
  </div><br/>
  <div class="mb-3">
    <input type="password" class="form-control" name="password", placeholder="Password" required>
  </div>
  <br/>
  <button type="submit" class="btn btn-secondary">Login</button>
	
</form>
</div>

{% endif %}

{% endblock %}

talentsystem/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Talent_System</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% load static %}
      {% if user.is_authenticated %}



  
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           New
          </a>
          <ul class="dropdown-menu">
            
        <li >
          <a  class="dropdown-item" href="{% url 'add_record' %}">+ Company Record</a>
        </li>
           <li >
          <a  class="dropdown-item" href="{% url 'add_employee' %}">+ Employee Record</a>
        </li>
        
        <li >
          <a  class="dropdown-item" href="{% url 'upload' %}">+Bulk Upload</a>
        </li>
          <li >
          <a  class="dropdown-item" href="{% url 'add_department' %}">+ Department Record</a>
        </li>
       
        
          </ul>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'company_details' %}">View-Company Details</a>
        </li>
      </ul>
    </div>
  </div>

</nav>
        


      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Login</a>
        </li>        
      {% endif %}
        
      </ul>
      
    </div>
  </div>
</nav>

talentsystem/templates/register.html
{% extends 'base.html' %}
{% block content %}


<div class="col-md-6 offset-md-3">
<h1>Register</h1>
<br/>

<form method="POST" action="">
	{% csrf_token %}
	{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Your Form Has Errors
			  {% for field in form %}
			  	{% if field.errors %}
			  		{{ field.errors }}
			  	{% endif %}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endif %}

	{{ form.as_p }}

	<br/>
	  <button type="submit" class="btn btn-secondary">Register</button>
	</form>
	<br/>


<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>



</div>

{% endblock %}